### ISSUE TITLE
Unable to Upload Emojis with Team Account

### ISSUE THREAD

**Issue by rowteeme** [masudhossain/queue-desktop#1]
**Environment:** Webapp / Chrome 
**Account Type:** Team 

**Steps to Reproduce:**
1. Add Emoji Plugin 
2. Navigate to a VOD replay
3. Click Upload Icon from Overlay

**Expected Behavior:** User is able to upload an emoji from hard drive
**Actual Behavior:** User sees "Unlock Emojis" call-to-action

**Screenshot:** https://cl.ly/c6acc3628763

**Comment by masudhossain** [comment]
Going to be changing the user experience flow for this and most likely make it free.
