### ISSUE TITLE
Some Canvas Tools appear underneath the video player/progress control bar

### ISSUE THREAD

**Issue by rowteeme** [masudhossain/queue-desktop#2]
**Environment:** Windows/Chrome
**Account Type:** Team
**Steps to Reproduce**
1. Navigate to VOD Replay
2. Hover over Color Wheel or Shapes icon

**Expected Behavior:** User sees caret with keyboard shortcut / description of tool (i think?)
**Actual Behavior:** User sees bottom of caret but player and progress control bar are overlaid on top obscuring label for the tool

Tough to get screenshot using my screenshot tool.

**Comment by masudhossain** [comment]
Fixed!
